# Generated by Django 5.2.9 on 2025-12-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Can manage users'), ('can_view_reports', 'Can view reports'), ('can_edit_courses', 'Can edit courses')]},
        ),
    ]
